/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-03-06 04:58:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.*;

public final class displayModel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<HTML>\n");
      out.write("  <HEAD>\n");
      out.write("    <TITLE>Model information</TITLE>\n");
      out.write("    \n");
      out.write("  </HEAD>\n");
      out.write("\n");
      out.write("    <BODY>\n");
      out.write("        <H2>");
 out.println("Model Updated Successfully"); 
      out.write("</H2>\n");
      out.write("        <H3>");
 out.println("Below is what you selected:"); 
      out.write("</H3>\n");
      out.write("        ");
 
        	HttpSession currentReqSession = request.getSession(false);
        	if (currentReqSession == null) {
		
      out.write("\t\t<p>The session is timed out</p> ");

        		return;
         	}
        	Automobile automobileModel = (Automobile) currentReqSession.getAttribute("automobileModel");
        	if (automobileModel == null){
    	
      out.write("\t\t<p>Failure to display Model details</p> ");

    			return;
    		}
        
      out.write("\n");
      out.write("        \n");
      out.write("        <Form>\n");
      out.write("        <TABLE border=\"1\">\n");
      out.write("        <TR><TD> ");
 out.println(automobileModel.getName()); 
      out.write("</TD>\n");
      out.write("        \t<TD>Basic Price</TD>\n");
      out.write("        \t<TD> ");
 out.println((int)automobileModel.getBasePrice()); 
      out.write("</TD>\n");
      out.write("        </TR>\n");
      out.write("        <TR><TD>Model</TD>\n");
      out.write("        \t<TD>");
 out.println(automobileModel.getModel()); 
      out.write("</TD>\n");
      out.write("        \t<TD></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t<TR><TD>Make</TD>\n");
      out.write("\t\t\t<TD>");
 out.println(automobileModel.getMake()); 
      out.write("</TD>\n");
      out.write("\t\t\t<TD></TD>\n");
      out.write("\t\t</TR>\n");
      out.write("\t\t");

			String[] optSetsNames = automobileModel.getOptionSetNames();
			for (int i=0; i < optSetsNames.length; i++){
	        	out.println("<TR><TD>" + optSetsNames[i] +"</TD>");
	        	out.println("<TD>" + automobileModel.getOptionChoice(optSetsNames[i])+ "</TD>");
	        	out.println("<TD>" + automobileModel.getOptionChoicePrice(optSetsNames[i])+ "</TD>");
	        	out.println("</TR>");
	        }
		
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<TR><TD>Total Price</TD>\n");
      out.write("\t\t\t<TD></TD>\n");
      out.write("\t\t\t<TD>");
 out.println(automobileModel.calculateTotalPrice());
      out.write("</TD>\n");
      out.write("\t\t</TR>\n");
      out.write("        </TABLE>\n");
      out.write("        </Form>\n");
      out.write("        \n");
      out.write("   </BODY>\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
